# Generated by Django 6.0.3 on 2026-04-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Cash Deposit'), ('BUY_SHARE', 'Buy Shares from Club'), ('SELL_SHARE', 'Sell Shares to Club'), ('TRANSFER', 'Transfer Equity')], max_length=20),
        ),
    ]
